[book]
title = "Kubewarden Kubernetes Policy Engine"
description = "Documentation of Kubewarden project"
authors = ["Kubewarden Developers"]
language = "en"
multilingual = false
src = "src"


[output.html]
git-repository-url = "https://github.com/kubewarden/docs"
edit-url-template = "https://github.com/kubewarden/docs/edit/main/{path}"
site-url = "/"
cname = "docs.kubewarden.io"
google-analytics = "UA-56382716-13"
