[book]
title = "Kubewarden Kubernetes Policy Engine"
description = "Documentation of Kubewarden project"
authors = ["Flavio Castelli", "Rafael Fernández López"]
language = "en"
multilingual = false
src = "src"


[output.html]
git-repository-url = "https://github.com/kubewarden/docs"
git-repository-edit-url-template = "https://github.com/kubewarden/docs/edit/main/{path}"
site-url = "/"
cname = "docs.kubewarden.io"
