[book]
authors = ["Flavio Castelli"]
language = "en"
multilingual = false
src = "src"
title = "Kubewarden Kubernetes Policy Engine"
git-repository-url = "https://github.com/kubewarden/kubewarden-book"
site-url = "/"
