name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main docs repo
<<<<<<< HEAD
        uses: actions/checkout@v3
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
=======
        uses: actions/checkout@v2
      - name: Setup Docusaurus
        uses: actions/setup-node@v2
>>>>>>> 52a595110fb15d2174390f0933caff5a8223aeb3
        with:
          node-version: 16.x
          cache: yarn
      - name: Build website
        run: |
          yarn install --frozen-lockfile
          yarn build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
