on: [pull_request]
name: Continuous integration

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main docs repo
        uses: actions/checkout@v2
      - name: Setup Docusaurus
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      - name: Build website
        run: |
          yarn install --frozen-lockfile
          yarn build
